CREATE DATABASE IF NOT EXISTS `demo` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

USE `demo`;

CREATE TABLE IF NOT EXISTS `t_user` (
    `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键',
    `username` VARCHAR(50) NOT NULL COMMENT '用户名',
    `phone` VARCHAR(255) DEFAULT NULL COMMENT '手机号（加密存储）',
    `id_card` VARCHAR(255) DEFAULT NULL COMMENT '身份证号（加密存储）',
    `email` VARCHAR(255) DEFAULT NULL COMMENT '邮箱（加密存储）',
    `age` INT DEFAULT NULL COMMENT '年龄',
    `create_time` DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `update_time` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='用户表';

CREATE TABLE IF NOT EXISTS `t_employee` (
    `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '主键',
    `name` VARCHAR(50) NOT NULL COMMENT '姓名',
    `phone` VARCHAR(255) DEFAULT NULL COMMENT '手机号（加密存储）',
    `id_card` VARCHAR(255) DEFAULT NULL COMMENT '身份证号（加密存储）',
    `bank_card` VARCHAR(255) DEFAULT NULL COMMENT '银行卡号（加密存储）',
    `salary` DECIMAL(10,2) DEFAULT NULL COMMENT '薪资',
    `department` VARCHAR(50) DEFAULT NULL COMMENT '部门',
    `create_time` DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    `update_time` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='员工表';
